galaxy_info:
  author: Pythian
  description: Installs Rsyslog.
  company: Pythian
  license: "license (BSD, MIT)"

  min_ansible_version: 2.2.1.0

  platforms:
    - name: Ubuntu
      versions:
      - xenial

  galaxy_tags:
    - rsyslog

dependencies: []
