---
# user-configurable defaults

java_version: 8
java_subversion: 152
java_jdk_checksum:

java_url_modifier: ""
java_download_path: /tmp
java_download_from_oracle: true
java_remove_download: true
java_install_jce: false

java_set_javahome: false
