---
# file: config.yml
- name: Copy rsyslog.conf file
  template:
    src: rsyslog.conf.j2
    dest: "/etc/rsyslog.conf"
    mode: 0644

- name: Copy rsyslog.conf file
  template:
    src: 50-default.conf.j2
    dest: "/etc/rsyslog.d/50-default.conf"
    mode: 0644
