---
# checking if required variables are set

- name: Checking if required variables are set
  fail: msg="{{ item }} is not defined"
  when: not (item is defined)
  with_items:
    - java_version
    - java_subversion
    - java_install_jce
