---
# Top-level installer for Oracle JDK

- block:

    - name: Check for an existing JDK tarball
      stat:
        path: "{{ java_download_path }}/{{ jdk_tarball_file }}.tar.gz"
      register: java_jdk_tarball_check_result
      changed_when: false

    - name: Get the sha256 checksum of the JDK tarball
      shell: |
        sha256sum {{ java_download_path }}/{{ jdk_tarball_file }}.tar.gz | awk '{print $1}'
      register: java_jdk_tarball_checksum_result
      changed_when: false
      when: java_jdk_tarball_check_result.stat.exists == true

    - name: Remove JDK tarball if there is a checksum mismatch
      file:
        path: "{{ java_download_path }}/{{ jdk_tarball_file }}.tar.gz"
        state: absent
      when:
        - java_jdk_tarball_check_result.stat.exists == true
        - java_jdk_tarball_checksum_result.stdout != java_jdk_checksum

    - name: Download JDK tarball (as tar.gz file)
      get_url:
        url: "{{ jdk_tarball_url }}.tar.gz"
        headers:
          Cookie: 'oraclelicense=accept-securebackup-cookie'
        dest: "{{ java_download_path }}/{{ jdk_tarball_file }}.tar.gz"
        mode: 0640
        checksum: "sha256:{{ java_jdk_checksum }}"
        timeout: 600

  when: java_download_from_oracle|bool == true

- name: Copy tarball from local
  copy:
    src: "{{ playbook_dir }}/files/{{ jdk_tarball_file }}.tar.gz"
    dest: "{{ java_download_path }}/{{ jdk_tarball_file }}.tar.gz"
  when: java_download_from_oracle|bool == false

- name: mkdir for Java
  file:
    path: "{{ java_install_dir }}/jdk{{ jdk_version }}"
    state: directory
    owner: root
    group: root
    mode: "u=rwx,go=rx"

- name: Install JDK via tarball file
  unarchive:
    src: "{{ java_download_path }}/{{ jdk_tarball_file }}.tar.gz"
    dest: "{{ java_install_dir }}"
    owner: root
    group: root
    mode: "go-w"
    remote_src: yes

- block:

    - name: Make sure /etc/profile.d exists
      file: path=/etc/profile.d  state=directory

    - name: export JAVA_HOME
      template:
        src:  ../templates/java_home.sh.j2
        dest: /etc/profile.d/java_home.sh
        mode: "a+x"

  when: java_set_javahome

- name: Link "{{ java_install_dir }}/{{ java_default_link_name }}"
  file:
    src: "{{ java_install_dir }}/jdk{{ jdk_version }}"
    dest: "{{ java_install_dir }}/{{ java_default_link_name }}"
    state: link

- name: Alternatives link for "java"
  alternatives:
    name: java
    link: /usr/bin/java
    path: "{{ java_install_dir }}/{{ java_default_link_name }}/bin/java"

- name: Alternatives link for "javac"
  alternatives:
    name: javac
    link: /usr/bin/javac
    path: "{{ java_install_dir }}/{{ java_default_link_name }}/bin/javac"

- name: Alternatives link for "jar"
  alternatives:
    name: jar
    link: /usr/bin/jar
    path: "{{ java_install_dir }}/{{ java_default_link_name }}/bin/jar"

- name: Alternatives link for "java_sdk"
  alternatives:
    name: java_sdk
    link: /usr/lib/jvm/java
    path: "{{ java_install_dir }}/{{ java_default_link_name }}"

- name: Remove temporary downloaded files, if requested
  file: path={{ item }} state=absent
  with_items:
    - "{{ java_download_path }}/{{ jdk_tarball_file }}.tar.gz"
    - "{{ java_download_path }}/check-tarball-installed.sh"
  ignore_errors: true
  when: java_remove_download
