---
# handlers file for pythian.zookeeper

- name: restart zookeeper
  systemd:
    name: zookeeper
    state: restarted
    daemon_reload: yes
  when: not suppress_zookeeper_handlers

- name: enable zookeeper
  systemd:
    name: zookeeper
    enabled: yes
    daemon_reload: yes

- name: start zookeeper
  systemd:
    name: zookeeper
    state: started
    daemon_reload: yes
  when: not suppress_zookeeper_handlers

- name: systemd daemon reload
  systemd:
    daemon_reload: yes
