---
# tasks file for pythian.selinux

- import_tasks: check_vars.yml
  tags:
    - "pythian.selinux"
    - "pythian.selinux:check"
    - "pythian.check"
    ###########################
    - "VMLC.provision"
    - "VMLC.image_build"

- import_tasks: install.yml
  tags:
    - "pythian.selinux"
    - "pythian.selinux:install"
    ###########################
    - "VMLC.provision"
    - "VMLC.image_build"

- import_tasks: config.yml
  tags:
    - "pythian.selinux"
    - "pythian.selinux:config"
    ###########################
    - "VMLC.provision"
    - "VMLC.image_build"

- import_tasks: service.yml
  tags:
    - "pythian.selinux"
    - "pythian.selinux:service"
    ###########################
    - "VMLC.provision"
    - "VMLC.image_build"

- import_tasks: cleanup.yml
  tags:
    - "pythian.selinux"
    - "pythian.selinux:cleanup"
    ###########################
    - "VMLC.provision"
    - "VMLC.image_build"
