---
# vars file for serverspec_extended_types

serverspec_extended_types_gem_name: "serverspec-extended-types"
serverspec_extended_types_gem_file_temp_dir: "/tmp/ansible_roles/serverspec_extended_types"
